import { MATCH_TYPES } from '../constants/matchTypes';
import { SPLIT_TYPES } from '../constants/splitTypes';

export const DEFAULT_CATEGORIES = [
  { id: 'cat_groceries', name: 'Groceries', color: '#22c55e', icon: '🛒', sortOrder: 1, subcategories: [
    { id: 'sub_instore_grocery', parentId: 'cat_groceries', name: 'In-Store Grocery', sortOrder: 1 },
    { id: 'sub_online_grocery', parentId: 'cat_groceries', name: 'Online Grocery', sortOrder: 2 },
    { id: 'sub_warehouse_club', parentId: 'cat_groceries', name: 'Warehouse Club', sortOrder: 3 },
    { id: 'sub_specialty_food', parentId: 'cat_groceries', name: 'Specialty Food', sortOrder: 4 },
  ]},
  { id: 'cat_dining', name: 'Food & Dining', color: '#f97316', icon: '🍽️', sortOrder: 2, subcategories: [
    { id: 'sub_fast_food', parentId: 'cat_dining', name: 'Fast Food', sortOrder: 1 },
    { id: 'sub_restaurants', parentId: 'cat_dining', name: 'Restaurants', sortOrder: 2 },
    { id: 'sub_coffee', parentId: 'cat_dining', name: 'Coffee & Cafes', sortOrder: 3 },
    { id: 'sub_bars', parentId: 'cat_dining', name: 'Bars & Alcohol', sortOrder: 4 },
    { id: 'sub_food_delivery', parentId: 'cat_dining', name: 'Food Delivery', sortOrder: 5 },
  ]},
  { id: 'cat_shopping', name: 'Shopping', color: '#a855f7', icon: '🛍️', sortOrder: 3, subcategories: [
    { id: 'sub_online_order', parentId: 'cat_shopping', name: 'Online Order', sortOrder: 1 },
    { id: 'sub_dept_store', parentId: 'cat_shopping', name: 'Department Store', sortOrder: 2 },
    { id: 'sub_clothing', parentId: 'cat_shopping', name: 'Clothing', sortOrder: 3 },
    { id: 'sub_electronics', parentId: 'cat_shopping', name: 'Electronics', sortOrder: 4 },
    { id: 'sub_home_goods', parentId: 'cat_shopping', name: 'Home Goods', sortOrder: 5 },
  ]},
  { id: 'cat_transport', name: 'Auto & Transport', color: '#3b82f6', icon: '🚗', sortOrder: 4, subcategories: [
    { id: 'sub_gas', parentId: 'cat_transport', name: 'Gas', sortOrder: 1 },
    { id: 'sub_parking', parentId: 'cat_transport', name: 'Parking', sortOrder: 2 },
    { id: 'sub_rideshare', parentId: 'cat_transport', name: 'Rideshare', sortOrder: 3 },
    { id: 'sub_car_maintenance', parentId: 'cat_transport', name: 'Car Maintenance', sortOrder: 4 },
    { id: 'sub_tolls', parentId: 'cat_transport', name: 'Tolls', sortOrder: 5 },
    { id: 'sub_public_transit', parentId: 'cat_transport', name: 'Public Transit', sortOrder: 6 },
  ]},
  { id: 'cat_utilities', name: 'Utilities', color: '#eab308', icon: '💡', sortOrder: 5, subcategories: [
    { id: 'sub_electric', parentId: 'cat_utilities', name: 'Electric', sortOrder: 1 },
    { id: 'sub_internet', parentId: 'cat_utilities', name: 'Internet & Cable', sortOrder: 2 },
    { id: 'sub_phone', parentId: 'cat_utilities', name: 'Phone', sortOrder: 3 },
    { id: 'sub_water_gas', parentId: 'cat_utilities', name: 'Water & Gas', sortOrder: 4 },
  ]},
  { id: 'cat_healthcare', name: 'Healthcare & Pharmacy', color: '#ef4444', icon: '🏥', sortOrder: 6, subcategories: [
    { id: 'sub_pharmacy', parentId: 'cat_healthcare', name: 'Pharmacy', sortOrder: 1 },
    { id: 'sub_doctor', parentId: 'cat_healthcare', name: 'Doctor & Clinic', sortOrder: 2 },
    { id: 'sub_dental', parentId: 'cat_healthcare', name: 'Dental & Vision', sortOrder: 3 },
    { id: 'sub_hospital', parentId: 'cat_healthcare', name: 'Hospital', sortOrder: 4 },
    { id: 'sub_insurance', parentId: 'cat_healthcare', name: 'Health Insurance', sortOrder: 5 },
  ]},
  { id: 'cat_entertainment', name: 'Entertainment', color: '#ec4899', icon: '🎬', sortOrder: 7, subcategories: [
    { id: 'sub_streaming', parentId: 'cat_entertainment', name: 'Streaming', sortOrder: 1 },
    { id: 'sub_movies', parentId: 'cat_entertainment', name: 'Movies & Events', sortOrder: 2 },
    { id: 'sub_gaming', parentId: 'cat_entertainment', name: 'Gaming', sortOrder: 3 },
    { id: 'sub_sports', parentId: 'cat_entertainment', name: 'Sports & Recreation', sortOrder: 4 },
  ]},
  { id: 'cat_travel', name: 'Travel', color: '#06b6d4', icon: '✈️', sortOrder: 8, subcategories: [
    { id: 'sub_flights', parentId: 'cat_travel', name: 'Flights', sortOrder: 1 },
    { id: 'sub_hotels', parentId: 'cat_travel', name: 'Hotels & Lodging', sortOrder: 2 },
    { id: 'sub_car_rental', parentId: 'cat_travel', name: 'Car Rental', sortOrder: 3 },
    { id: 'sub_travel_activities', parentId: 'cat_travel', name: 'Activities & Tours', sortOrder: 4 },
  ]},
  { id: 'cat_subscriptions', name: 'Subscriptions & Memberships', color: '#8b5cf6', icon: '🔄', sortOrder: 9, subcategories: [
    { id: 'sub_streaming_mem', parentId: 'cat_subscriptions', name: 'Streaming & Membership', sortOrder: 1 },
    { id: 'sub_software', parentId: 'cat_subscriptions', name: 'Software & Apps', sortOrder: 2 },
    { id: 'sub_gym', parentId: 'cat_subscriptions', name: 'Gym & Fitness', sortOrder: 3 },
    { id: 'sub_news', parentId: 'cat_subscriptions', name: 'News & Media', sortOrder: 4 },
  ]},
  { id: 'cat_personal_care', name: 'Personal Care & Beauty', color: '#f43f5e', icon: '💅', sortOrder: 10, subcategories: [
    { id: 'sub_hair', parentId: 'cat_personal_care', name: 'Hair & Salon', sortOrder: 1 },
    { id: 'sub_spa', parentId: 'cat_personal_care', name: 'Spa & Wellness', sortOrder: 2 },
    { id: 'sub_cosmetics', parentId: 'cat_personal_care', name: 'Cosmetics & Skincare', sortOrder: 3 },
  ]},
  { id: 'cat_education', name: 'Education', color: '#10b981', icon: '📚', sortOrder: 11, subcategories: [
    { id: 'sub_tuition', parentId: 'cat_education', name: 'Tuition & Fees', sortOrder: 1 },
    { id: 'sub_books', parentId: 'cat_education', name: 'Books & Supplies', sortOrder: 2 },
    { id: 'sub_courses', parentId: 'cat_education', name: 'Online Courses', sortOrder: 3 },
  ]},
  { id: 'cat_home', name: 'Home & Garden', color: '#84cc16', icon: '🏠', sortOrder: 12, subcategories: [
    { id: 'sub_rent', parentId: 'cat_home', name: 'Rent & Mortgage', sortOrder: 1 },
    { id: 'sub_home_improvement', parentId: 'cat_home', name: 'Home Improvement', sortOrder: 2 },
    { id: 'sub_garden', parentId: 'cat_home', name: 'Garden & Outdoor', sortOrder: 3 },
    { id: 'sub_furniture', parentId: 'cat_home', name: 'Furniture & Decor', sortOrder: 4 },
  ]},
  { id: 'cat_technology', name: 'Technology', color: '#64748b', icon: '💻', sortOrder: 13, subcategories: [
    { id: 'sub_cloud', parentId: 'cat_technology', name: 'Cloud Services', sortOrder: 1 },
    { id: 'sub_devices', parentId: 'cat_technology', name: 'Devices & Gadgets', sortOrder: 2 },
    { id: 'sub_software_tech', parentId: 'cat_technology', name: 'Software & Licenses', sortOrder: 3 },
  ]},
  { id: 'cat_transfers', name: 'Transfers & Payments', color: '#94a3b8', icon: '💸', sortOrder: 14, subcategories: [
    { id: 'sub_p2p', parentId: 'cat_transfers', name: 'P2P Transfer', sortOrder: 1 },
    { id: 'sub_credit_payment', parentId: 'cat_transfers', name: 'Credit Card Payment', sortOrder: 2 },
    { id: 'sub_wire', parentId: 'cat_transfers', name: 'Wire Transfer', sortOrder: 3 },
  ]},
  { id: 'cat_income', name: 'Income', color: '#22d3ee', icon: '💰', sortOrder: 15, subcategories: [
    { id: 'sub_paycheck', parentId: 'cat_income', name: 'Paycheck', sortOrder: 1 },
    { id: 'sub_refund', parentId: 'cat_income', name: 'Refund & Cashback', sortOrder: 2 },
    { id: 'sub_other_income', parentId: 'cat_income', name: 'Other Income', sortOrder: 3 },
  ]},
  { id: 'cat_uncategorized', name: 'Uncategorized', color: '#6b7280', icon: '❓', sortOrder: 16, subcategories: [] },
];

export const DEFAULT_RULES = [
  // ─── WALMART ───
  { id: 'R001', keyword: 'WAL-MART', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Walmart', categoryId: 'cat_groceries', subcategoryId: 'sub_instore_grocery', priority: 10, enabled: true, notes: 'Walmart in-store grocery' },
  { id: 'R002', keyword: 'WALMART.COM', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Walmart', categoryId: 'cat_shopping', subcategoryId: 'sub_online_order', priority: 5, enabled: true, notes: 'Walmart online (higher priority than generic WAL-MART)' },
  { id: 'R003', keyword: 'WAL-MART FUEL', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Walmart Gas', categoryId: 'cat_transport', subcategoryId: 'sub_gas', priority: 3, enabled: true, notes: 'Walmart gas station' },
  { id: 'R004', keyword: 'WALMART GAS', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Walmart Gas', categoryId: 'cat_transport', subcategoryId: 'sub_gas', priority: 3, enabled: true, notes: 'Walmart gas station' },
  // ─── AMAZON ───
  { id: 'R005', keyword: 'AMAZON PRIME', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Amazon Prime', categoryId: 'cat_subscriptions', subcategoryId: 'sub_streaming_mem', priority: 5, enabled: true, notes: 'Amazon Prime membership' },
  { id: 'R006', keyword: 'AMAZON WEB', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Amazon Web Services', categoryId: 'cat_technology', subcategoryId: 'sub_cloud', priority: 5, enabled: true, notes: 'AWS cloud services' },
  { id: 'R007', keyword: 'AMAZON.COM', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Amazon', categoryId: 'cat_shopping', subcategoryId: 'sub_online_order', priority: 10, enabled: true, notes: 'Amazon online shopping' },
  { id: 'R008', keyword: 'AMZN MKTP', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Amazon', categoryId: 'cat_shopping', subcategoryId: 'sub_online_order', priority: 10, enabled: true, notes: 'Amazon marketplace' },
  // ─── FAST FOOD ───
  { id: 'R009', keyword: "MCDONALD'S", matchType: MATCH_TYPES.CONTAINS, normalizedVendor: "McDonald's", categoryId: 'cat_dining', subcategoryId: 'sub_fast_food', priority: 20, enabled: true, notes: '' },
  { id: 'R010', keyword: 'MCDONALDS', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: "McDonald's", categoryId: 'cat_dining', subcategoryId: 'sub_fast_food', priority: 20, enabled: true, notes: '' },
  { id: 'R011', keyword: 'CHICK-FIL-A', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Chick-fil-A', categoryId: 'cat_dining', subcategoryId: 'sub_fast_food', priority: 20, enabled: true, notes: '' },
  { id: 'R012', keyword: 'CHIPOTLE', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Chipotle', categoryId: 'cat_dining', subcategoryId: 'sub_fast_food', priority: 20, enabled: true, notes: '' },
  { id: 'R013', keyword: 'STARBUCKS', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Starbucks', categoryId: 'cat_dining', subcategoryId: 'sub_coffee', priority: 20, enabled: true, notes: '' },
  { id: 'R014', keyword: 'DUNKIN', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: "Dunkin'", categoryId: 'cat_dining', subcategoryId: 'sub_coffee', priority: 20, enabled: true, notes: '' },
  { id: 'R015', keyword: 'SUBWAY', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Subway', categoryId: 'cat_dining', subcategoryId: 'sub_fast_food', priority: 20, enabled: true, notes: '' },
  { id: 'R016', keyword: 'TACO BELL', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Taco Bell', categoryId: 'cat_dining', subcategoryId: 'sub_fast_food', priority: 20, enabled: true, notes: '' },
  { id: 'R017', keyword: "DOMINO'S", matchType: MATCH_TYPES.CONTAINS, normalizedVendor: "Domino's", categoryId: 'cat_dining', subcategoryId: 'sub_fast_food', priority: 20, enabled: true, notes: '' },
  { id: 'R018', keyword: 'PIZZA HUT', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Pizza Hut', categoryId: 'cat_dining', subcategoryId: 'sub_fast_food', priority: 20, enabled: true, notes: '' },
  { id: 'R019', keyword: 'BURGER KING', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Burger King', categoryId: 'cat_dining', subcategoryId: 'sub_fast_food', priority: 20, enabled: true, notes: '' },
  { id: 'R020', keyword: 'WENDYS', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: "Wendy's", categoryId: 'cat_dining', subcategoryId: 'sub_fast_food', priority: 20, enabled: true, notes: '' },
  { id: 'R021', keyword: "WENDY'S", matchType: MATCH_TYPES.CONTAINS, normalizedVendor: "Wendy's", categoryId: 'cat_dining', subcategoryId: 'sub_fast_food', priority: 20, enabled: true, notes: '' },
  { id: 'R022', keyword: 'PANERA', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Panera Bread', categoryId: 'cat_dining', subcategoryId: 'sub_fast_food', priority: 20, enabled: true, notes: '' },
  // ─── FOOD DELIVERY ───
  { id: 'R023', keyword: 'DOORDASH', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'DoorDash', categoryId: 'cat_dining', subcategoryId: 'sub_food_delivery', priority: 20, enabled: true, notes: '' },
  { id: 'R024', keyword: 'UBEREATS', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Uber Eats', categoryId: 'cat_dining', subcategoryId: 'sub_food_delivery', priority: 15, enabled: true, notes: '' },
  { id: 'R025', keyword: 'GRUBHUB', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Grubhub', categoryId: 'cat_dining', subcategoryId: 'sub_food_delivery', priority: 20, enabled: true, notes: '' },
  // ─── GAS STATIONS ───
  { id: 'R026', keyword: 'SHELL', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Shell', categoryId: 'cat_transport', subcategoryId: 'sub_gas', priority: 20, enabled: true, notes: '' },
  { id: 'R027', keyword: 'CHEVRON', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Chevron', categoryId: 'cat_transport', subcategoryId: 'sub_gas', priority: 20, enabled: true, notes: '' },
  { id: 'R028', keyword: 'EXXON', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'ExxonMobil', categoryId: 'cat_transport', subcategoryId: 'sub_gas', priority: 20, enabled: true, notes: '' },
  { id: 'R029', keyword: 'BP#', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'BP', categoryId: 'cat_transport', subcategoryId: 'sub_gas', priority: 20, enabled: true, notes: '' },
  { id: 'R030', keyword: 'CIRCLE K', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Circle K', categoryId: 'cat_transport', subcategoryId: 'sub_gas', priority: 20, enabled: true, notes: '' },
  { id: 'R031', keyword: 'QUIKTRIP', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'QuikTrip', categoryId: 'cat_transport', subcategoryId: 'sub_gas', priority: 20, enabled: true, notes: '' },
  { id: 'R032', keyword: '7-ELEVEN FUEL', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: '7-Eleven', categoryId: 'cat_transport', subcategoryId: 'sub_gas', priority: 20, enabled: true, notes: '' },
  { id: 'R033', keyword: 'SPEEDWAY', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Speedway', categoryId: 'cat_transport', subcategoryId: 'sub_gas', priority: 20, enabled: true, notes: '' },
  { id: 'R034', keyword: 'WAWA', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Wawa', categoryId: 'cat_transport', subcategoryId: 'sub_gas', priority: 20, enabled: true, notes: '' },
  // ─── GROCERIES ───
  { id: 'R035', keyword: 'KROGER', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Kroger', categoryId: 'cat_groceries', subcategoryId: 'sub_instore_grocery', priority: 20, enabled: true, notes: '' },
  { id: 'R036', keyword: 'HEB', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'H-E-B', categoryId: 'cat_groceries', subcategoryId: 'sub_instore_grocery', priority: 20, enabled: true, notes: '' },
  { id: 'R037', keyword: 'WHOLE FOODS', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Whole Foods', categoryId: 'cat_groceries', subcategoryId: 'sub_specialty_food', priority: 20, enabled: true, notes: '' },
  { id: 'R038', keyword: "TRADER JOE'S", matchType: MATCH_TYPES.CONTAINS, normalizedVendor: "Trader Joe's", categoryId: 'cat_groceries', subcategoryId: 'sub_specialty_food', priority: 20, enabled: true, notes: '' },
  { id: 'R039', keyword: 'ALDI', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Aldi', categoryId: 'cat_groceries', subcategoryId: 'sub_instore_grocery', priority: 20, enabled: true, notes: '' },
  { id: 'R040', keyword: 'PUBLIX', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Publix', categoryId: 'cat_groceries', subcategoryId: 'sub_instore_grocery', priority: 20, enabled: true, notes: '' },
  { id: 'R041', keyword: 'COSTCO WHSE', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Costco', categoryId: 'cat_groceries', subcategoryId: 'sub_warehouse_club', priority: 20, enabled: true, notes: '' },
  { id: 'R042', keyword: 'COSTCO', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Costco', categoryId: 'cat_groceries', subcategoryId: 'sub_warehouse_club', priority: 21, enabled: true, notes: '' },
  { id: 'R043', keyword: "SAM'S CLUB", matchType: MATCH_TYPES.CONTAINS, normalizedVendor: "Sam's Club", categoryId: 'cat_groceries', subcategoryId: 'sub_warehouse_club', priority: 20, enabled: true, notes: '' },
  { id: 'R044', keyword: 'SAFEWAY', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Safeway', categoryId: 'cat_groceries', subcategoryId: 'sub_instore_grocery', priority: 20, enabled: true, notes: '' },
  { id: 'R045', keyword: 'WEGMANS', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Wegmans', categoryId: 'cat_groceries', subcategoryId: 'sub_instore_grocery', priority: 20, enabled: true, notes: '' },
  { id: 'R046', keyword: 'TARGET', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Target', categoryId: 'cat_shopping', subcategoryId: 'sub_dept_store', priority: 20, enabled: true, notes: '' },
  // ─── UTILITIES ───
  { id: 'R047', keyword: 'AT&T', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'AT&T', categoryId: 'cat_utilities', subcategoryId: 'sub_phone', priority: 20, enabled: true, notes: '' },
  { id: 'R048', keyword: 'VERIZON', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Verizon', categoryId: 'cat_utilities', subcategoryId: 'sub_phone', priority: 20, enabled: true, notes: '' },
  { id: 'R049', keyword: 'T-MOBILE', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'T-Mobile', categoryId: 'cat_utilities', subcategoryId: 'sub_phone', priority: 20, enabled: true, notes: '' },
  { id: 'R050', keyword: 'COMCAST', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Comcast', categoryId: 'cat_utilities', subcategoryId: 'sub_internet', priority: 20, enabled: true, notes: '' },
  { id: 'R051', keyword: 'XFINITY', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Xfinity', categoryId: 'cat_utilities', subcategoryId: 'sub_internet', priority: 20, enabled: true, notes: '' },
  { id: 'R052', keyword: 'SPECTRUM', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Spectrum', categoryId: 'cat_utilities', subcategoryId: 'sub_internet', priority: 20, enabled: true, notes: '' },
  { id: 'R053', keyword: 'ELECTRIC', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Electric Company', categoryId: 'cat_utilities', subcategoryId: 'sub_electric', priority: 30, enabled: true, notes: '' },
  { id: 'R054', keyword: 'DUKE ENERGY', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Duke Energy', categoryId: 'cat_utilities', subcategoryId: 'sub_electric', priority: 20, enabled: true, notes: '' },
  { id: 'R055', keyword: 'COX COMM', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Cox', categoryId: 'cat_utilities', subcategoryId: 'sub_internet', priority: 20, enabled: true, notes: '' },
  // ─── HEALTHCARE ───
  { id: 'R056', keyword: 'CVS PHARMACY', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'CVS Pharmacy', categoryId: 'cat_healthcare', subcategoryId: 'sub_pharmacy', priority: 15, enabled: true, notes: '' },
  { id: 'R057', keyword: 'CVS', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'CVS', categoryId: 'cat_healthcare', subcategoryId: 'sub_pharmacy', priority: 20, enabled: true, notes: '' },
  { id: 'R058', keyword: 'WALGREENS', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Walgreens', categoryId: 'cat_healthcare', subcategoryId: 'sub_pharmacy', priority: 20, enabled: true, notes: '' },
  { id: 'R059', keyword: 'RITE AID', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Rite Aid', categoryId: 'cat_healthcare', subcategoryId: 'sub_pharmacy', priority: 20, enabled: true, notes: '' },
  { id: 'R060', keyword: 'PHARMACY', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Pharmacy', categoryId: 'cat_healthcare', subcategoryId: 'sub_pharmacy', priority: 30, enabled: true, notes: '' },
  { id: 'R061', keyword: 'URGENT CARE', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Urgent Care', categoryId: 'cat_healthcare', subcategoryId: 'sub_doctor', priority: 25, enabled: true, notes: '' },
  { id: 'R062', keyword: 'HOSPITAL', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Hospital', categoryId: 'cat_healthcare', subcategoryId: 'sub_hospital', priority: 25, enabled: true, notes: '' },
  // ─── TRAVEL ───
  { id: 'R063', keyword: 'UBER', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Uber', categoryId: 'cat_transport', subcategoryId: 'sub_rideshare', priority: 15, enabled: true, notes: '' },
  { id: 'R064', keyword: 'LYFT', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Lyft', categoryId: 'cat_transport', subcategoryId: 'sub_rideshare', priority: 20, enabled: true, notes: '' },
  { id: 'R065', keyword: 'AIRBNB', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Airbnb', categoryId: 'cat_travel', subcategoryId: 'sub_hotels', priority: 20, enabled: true, notes: '' },
  { id: 'R066', keyword: 'DELTA', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Delta Airlines', categoryId: 'cat_travel', subcategoryId: 'sub_flights', priority: 20, enabled: true, notes: '' },
  { id: 'R067', keyword: 'AMERICAN AIR', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'American Airlines', categoryId: 'cat_travel', subcategoryId: 'sub_flights', priority: 20, enabled: true, notes: '' },
  { id: 'R068', keyword: 'SOUTHWEST', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Southwest Airlines', categoryId: 'cat_travel', subcategoryId: 'sub_flights', priority: 20, enabled: true, notes: '' },
  { id: 'R069', keyword: 'UNITED AIRLINES', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'United Airlines', categoryId: 'cat_travel', subcategoryId: 'sub_flights', priority: 20, enabled: true, notes: '' },
  { id: 'R070', keyword: 'MARRIOTT', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Marriott', categoryId: 'cat_travel', subcategoryId: 'sub_hotels', priority: 20, enabled: true, notes: '' },
  { id: 'R071', keyword: 'HILTON', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Hilton', categoryId: 'cat_travel', subcategoryId: 'sub_hotels', priority: 20, enabled: true, notes: '' },
  // ─── STREAMING ───
  { id: 'R072', keyword: 'NETFLIX', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Netflix', categoryId: 'cat_subscriptions', subcategoryId: 'sub_streaming_mem', priority: 20, enabled: true, notes: '' },
  { id: 'R073', keyword: 'SPOTIFY', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Spotify', categoryId: 'cat_subscriptions', subcategoryId: 'sub_streaming_mem', priority: 20, enabled: true, notes: '' },
  { id: 'R074', keyword: 'HULU', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Hulu', categoryId: 'cat_subscriptions', subcategoryId: 'sub_streaming_mem', priority: 20, enabled: true, notes: '' },
  { id: 'R075', keyword: 'DISNEY+', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Disney+', categoryId: 'cat_subscriptions', subcategoryId: 'sub_streaming_mem', priority: 20, enabled: true, notes: '' },
  { id: 'R076', keyword: 'DISNEY PLUS', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Disney+', categoryId: 'cat_subscriptions', subcategoryId: 'sub_streaming_mem', priority: 20, enabled: true, notes: '' },
  { id: 'R077', keyword: 'APPLE.COM/BILL', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Apple', categoryId: 'cat_subscriptions', subcategoryId: 'sub_software', priority: 20, enabled: true, notes: '' },
  { id: 'R078', keyword: 'YOUTUBE PREMIUM', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'YouTube', categoryId: 'cat_subscriptions', subcategoryId: 'sub_streaming_mem', priority: 20, enabled: true, notes: '' },
  { id: 'R079', keyword: 'HBO MAX', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'HBO Max', categoryId: 'cat_subscriptions', subcategoryId: 'sub_streaming_mem', priority: 20, enabled: true, notes: '' },
  { id: 'R080', keyword: 'MAX.COM', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Max', categoryId: 'cat_subscriptions', subcategoryId: 'sub_streaming_mem', priority: 20, enabled: true, notes: '' },
  // ─── TRANSFERS / P2P ───
  { id: 'R081', keyword: 'ZELLE', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Zelle', categoryId: 'cat_transfers', subcategoryId: 'sub_p2p', priority: 20, enabled: true, notes: 'Review - may not be a true expense' },
  { id: 'R082', keyword: 'VENMO', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Venmo', categoryId: 'cat_transfers', subcategoryId: 'sub_p2p', priority: 20, enabled: true, notes: 'Review - may not be a true expense' },
  { id: 'R083', keyword: 'PAYPAL', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'PayPal', categoryId: 'cat_transfers', subcategoryId: 'sub_p2p', priority: 20, enabled: true, notes: 'Review - may not be a true expense' },
  { id: 'R084', keyword: 'ACH TRANSFER', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'ACH Transfer', categoryId: 'cat_transfers', subcategoryId: 'sub_wire', priority: 20, enabled: true, notes: 'Review - may not be a true expense' },
  { id: 'R085', keyword: 'WIRE TRANSFER', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Wire Transfer', categoryId: 'cat_transfers', subcategoryId: 'sub_wire', priority: 20, enabled: true, notes: 'Review - may not be a true expense' },
  // ─── MISC RETAIL ───
  { id: 'R086', keyword: 'BEST BUY', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Best Buy', categoryId: 'cat_shopping', subcategoryId: 'sub_electronics', priority: 20, enabled: true, notes: '' },
  { id: 'R087', keyword: 'HOME DEPOT', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: 'Home Depot', categoryId: 'cat_home', subcategoryId: 'sub_home_improvement', priority: 20, enabled: true, notes: '' },
  { id: 'R088', keyword: "LOWE'S", matchType: MATCH_TYPES.CONTAINS, normalizedVendor: "Lowe's", categoryId: 'cat_home', subcategoryId: 'sub_home_improvement', priority: 20, enabled: true, notes: '' },
  { id: 'R089', keyword: 'LOWES', matchType: MATCH_TYPES.CONTAINS, normalizedVendor: "Lowe's", categoryId: 'cat_home', subcategoryId: 'sub_home_improvement', priority: 21, enabled: true, notes: '' },
].map(r => ({ ...r, createdAt: new Date().toISOString() }));

export const DEFAULT_SETTINGS = {
  defaultSplit: { type: SPLIT_TYPES.FULL, divisor: 2, customAmount: 0 },
  currency: 'USD',
  currencySymbol: '$',
  dateFormat: 'MM/DD/YYYY',
  fiscalYearStart: 1,
  duplicateWindow: 3,
  flagLargeTransactionsThreshold: 200,
  flagUncategorized: true,
  monthlyBudget: 3000,
  monthlyIncome: 5000,
  theme: 'light',
  bankMappingOverrides: {},
};
